baseurl = "http://vjeantet.fr"
languageCode = "fr-FR"
title = "Valère JEANTET"
paginate = 5
DisqusShortname = "vjeantet"
Copyright = "All rights reserved - 2015"

[params]
  description = "Whatever the mind of man can conceive and believe, it can achieve."
  cover = "images/cover_polenord.jpg"
  author = "Valère JEANTET"
  authorlocation = "Paris, France"
  authorwebsite = "http://vjeantet.fr"
  bio= "IT software and Security Engineer, Open source enthusiast."
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  githubName = "vjeantet"
  twitterName = "vjeantet"


[permalinks]
  post = "/:slug/"