name = "Casper v0.9.4"
license = "MIT"
licenselink = "https://github.com/vjeantet/vjeantet.fr/blob/master/themes/casper-v094/LICENSE.md"
description = "Casper theme from Ghost Foundation v0.9.4"
homepage = "http://vjeantet.fr/"
tags = ["", ""]
features = ["", ""]

[author]
  name = "Valere JEANTET"
  homepage = "http://vjeantet.fr"

[original]
  name = "Casper v0.9.4"
  homepage = "https://github.com/TryGhost/Casper"
  repo = "https://github.com/TryGhost/Casper"
